baseURL = "https://peoray-blog.netlify.com/"
title = "Emmanuel Raymond"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Emmanuel Raymond"
googleAnalytics = "UA-131778153-1"
disqusShortname = "peoray"

[blackfriday] 
    hrefTargetBlank = true

[Privacy]

[Privacy.disqus]
    disable = false

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Emmanuel Raymond"
    # profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Emmanuel Raymond. I'm a developer and an Autodidact. "
    description = "Join my adventure in discovering everything about Web Programming and Life. Everything on this website is for you, ad-free."
    github = "https://github.com/peoray"
    # gitlab = "https://gitlab.com/XXX"
    linkedin = "https://www.linkedin.com/in/emmanuel-raymond-b1421b128/"
    # gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/super_raay"
    # stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "peorayy@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    # shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false

[Permalinks]
    # post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "monthly reviews"
    url = "/monthly-review/"
    weight = 2

[[menu.main]]
    name = "tutorials"
    url = "/tutorials"
    weight = 3

[[menu.main]]
    name = "tech"
    url = "/technology"
    weight = 4

[[menu.main]]
    name = "personal"
    url = "/thoughts"
    weight = 5