baseURL = "https://blog.peoray.com"
title = "Emmanuel Raymond"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Emmanuel Raymond"
googleAnalytics = "UA-131778153-1"
disqusShortname = "peoray"

enableRobotsTXT = true
# canonifyURLs = true


pygmentsCodeFences = true
# PygmentsStyle = "monokai"
# pygmentsUseClasses = true
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClassic = true 

enableInlineShortcodes = true

 
[blackfriday] 
    hrefTargetBlank = true
    plainIDAnchors = true
    extension = [
        'hardLineBreak'
    ]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Emmanuel Raymond"
    # profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Emmanuel Raymond. I'm a developer and an Autodidact. "
    description = "Join my adventure in discovering everything about Web Programming and Life. Everything on this website is for you, ad-free."
    github = "https://github.com/peoray"
    # gitlab = "https://gitlab.com/XXX"
    linkedin = "https://www.linkedin.com/in/emmanuel-raymond-b1421b128/"
    # gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/peoray_"
    # stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    email = "peorayy@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    # shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"
    cloudinary_url = "https://res.cloudinary.com/peoray/image/upload"


[Permalinks]
    # post = "/:year/:month/:day/:filename/"
    post = "/:filename/"
    # thoughts = "/:filename/"
    

# [[menu.main]]
    #name = "home"
    #url = "/"
    #weight = 1

# [[menu.main]]
    #name = "Tech & Tutorials"
    #url = "/tech_tutorials"
    #weight = 2

# [[menu.main]]
    #name = "personal"
    #url = "/thoughts"
    #weight = 3